version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ufam-explore
    environment:
      POSTGRES_DB: ufam-explore
      POSTGRES_USER: ufam-explore
      POSTGRES_PASSWORD: ufam-explore
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: fernandaalice2003@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Faod318n
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data: