import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  profileSection: {
    width: "100%",
    backgroundColor: "rgba(0, 24, 109, 0.9)",
    alignItems: "center",
    paddingVertical: 50,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    marginBottom: 50,
  },
  editableSection: {
    width: "80%",
    alignItems: "center",
  },
  dropdownButtonStyle: {
    width: "100%",
    height: 50,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  dropdownButtonTxtStyle: {
    flex: 1,
    fontSize: 16,
    color: "#444",
    textAlign: "left",
  },
  dropdownButtonArrowStyle: {
    fontSize: 24,
    color: "gray",
  },
  dropdownMenuStyle: {
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
  },
  dropdownItemStyle: {
    width: "100%",
    flexDirection: "row",
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 8,
  },
  dropdownItemTxtStyle: {
    flex: 1,
    fontSize: 16,
    color: "#444",
    textAlign: "left",
  },
  errorText: {
    color: "red",
    paddingBottom: 5,
  },
  boxInput: {
    backgroundColor: "rgba(0, 0, 139, 0.1)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "darkblue",
    width: "100%",
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  profileImageContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    borderRadius: 50,
    width: 100,
    height: 100,
  },
  backButton: {
    position: "absolute",
    top: 40,
    left: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  profileName: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
  },
  texto: {
    color: "darkblue",
    fontSize: 20,
    alignSelf: "flex-start",
    paddingHorizontal: 5,
    paddingTop: 10,
  },
  cameraIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 12,
    padding: 5,
  },
  textoAlternativo: {
    color: "black",
    fontSize: 15,
    marginBottom: 20,
  },
  inputField: {
    flex: 1,
    paddingLeft: 10,
    fontSize: 16,
  },
  BoxInput: {
    backgroundColor: "rgba(0, 0, 139, 0.1)",
    width: "100%",
    height: 40,
    borderRadius: 10,
    paddingLeft: 10,
    borderColor: "darkblue",
  },
  confirmButton: {},
  confirmButtonContainer: {
    paddingVertical: 10,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
});
