import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 40,
  },
  logo: {
    width: 200,
    height: 50,
    marginBottom: 10,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  searchInput: {
    width: '78%',
    alignSelf: 'center',
    height: 40,
    borderColor: '#4A6EA8',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginHorizontal: 20,
    marginBottom: 10,
    fontSize: 16,
  },
  filterContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4A6EA8',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginHorizontal: 8,
    marginBottom: 10,
    flexShrink: 1,
  },
  filterButtonSelected: {
    backgroundColor: '#4A6EA8',
  },
  filterText: {
    color: '#4A6EA8',
    marginRight: 5,
    textAlign: 'center',
  },
  filterTextSelected: {
    color: '#FFF',
    marginRight: 5,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  clearButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginHorizontal: 5,
  },
  clearButtonText: {
    color: '#FFF',
    fontSize: 16,
  },
  fetchButton: {
    backgroundColor: '#002E7D',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginHorizontal: 5,
  },
  fetchButtonText: {
    color: '#FFF',
    fontSize: 16,
  },
  helpText: {
    width: '80%',
    alignSelf: 'center',
    textAlign: 'center',
    color: '#002E7D',
    fontSize: 14,
    marginVertical: 15,
  },
  postContainer: {
    marginVertical: 10,
    padding: 15,
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    width: '100%',
  },
  postTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  postText: {
    fontSize: 16,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyStateText: {
    marginTop: 20,
    fontSize: 16,
    color: '#002E7D',
    width: '80%',
    textAlign: 'center',
  },
});
