export const cursos: string[] = [
  'Agronomia',
  'Engenharia Florestal',
  'Engenharia de Pesca',
  'Zootecnia',
  'Engenharia de Alimentos',
  'Biotecnologia',
  'Ciências Biológicas',
  'Ciências Naturais',
  'Educação Física',
  'Enfermagem',
  'Farmácia',
  'Fisioterapia',
  'Medicina',
  'Odontologia',
  'Arquitetura e Urbanismo',
  'Ciência da Computação',
  'Design',
  'Engenharia Civil',
  'Engenharia da Computação',
  'Engenharia de Materiais',
  'Engenharia de Petróleo e Gás',
  'Engenharia de Produção',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Química',
  'Estatística',
  'Física',
  'Geologia',
  'Matemática',
  'Química',
  'Engenharia de Software',
  'Administração',
  'Arquivologia',
  'Artes Visuais',
  'Biblioteconomia',
  'Ciências Contábeis',
  'Ciências Econômicas',
  'Ciências Sociais',
  'Comunicação Social',
  'Direito',
  'Filosofia',
  'Geografia',
  'História',
  'Letras',
  'Música',
  'Pedagogia',
  'Psicologia',
  'Serviço Social',
];

export const areas = ['Biológicas', 'Exatas', 'Humanas'];

export const cursosPorArea: { [key: string]: string[] } = {
  Biológicas: [
    'Agronomia',
    'Engenharia Florestal',
    'Engenharia de Pesca',
    'Zootecnia',
    'Engenharia de Alimentos',
    'Biotecnologia',
    'Ciências Biológicas',
    'Ciências Naturais',
    'Educação Física',
    'Enfermagem',
    'Farmácia',
    'Fisioterapia',
    'Medicina',
    'Odontologia',
  ],
  Exatas: [
    'Arquitetura e Urbanismo',
    'Ciência da Computação',
    'Design',
    'Engenharia Civil',
    'Engenharia da Computação',
    'Engenharia de Materiais',
    'Engenharia de Petróleo e Gás',
    'Engenharia de Produção',
    'Engenharia Elétrica',
    'Engenharia Mecânica',
    'Engenharia Química',
    'Estatística',
    'Física',
    'Geologia',
    'Matemática',
    'Química',
    'Engenharia de Software',
  ],
  Humanas: [
    'Administração',
    'Arquivologia',
    'Artes Visuais',
    'Biblioteconomia',
    'Ciências Contábeis',
    'Ciências Econômicas',
    'Ciências Sociais',
    'Comunicação Social',
    'Direito',
    'Filosofia',
    'Geografia',
    'História',
    'Letras',
    'Música',
    'Pedagogia',
    'Psicologia',
    'Serviço Social',
  ],
};
export const tempos = ['Hoje', 'Esta semana', 'Este mês'];
