name: Deploy Backend to Master

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Busca apenas a branch de desenvolvimento e seu pai direto

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Nest CLI Globally
        run: |
          npm install -g @nestjs/cli

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          nest build

      - name: Deploy to Master Branch
        run: |
          cd backend
          git fetch origin
          git checkout master
          git pull origin master
          git merge --no-ff ${{ github.sha }}
          git push origin master
