name: Deploy Backend to Master

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Backend
        run: |
          cd backend
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email "fernandaalice2003@gmail.com"
          git config --global user.name "feralice"

      - name: Deploy to Master Branch
        run: |
          cd backend
          git checkout master
          git merge --no-ff ${{ github.sha }}
          git push origin master
